# Auto-generated homoglyph mapping
# Generated from dataset analysis

HOMOGLYPH_MAP = {
    'ℍ': 'H',  # DOUBLE-STRUCK CAPITAL H
    '１': '1',  # FULLWIDTH DIGIT ONE
    '３': '3',  # FULLWIDTH DIGIT THREE
    '８': '8',  # FULLWIDTH DIGIT EIGHT
    'ａ': 'a',  # FULLWIDTH LATIN SMALL LETTER A
    'ｄ': 'd',  # FULLWIDTH LATIN SMALL LETTER D
    'ｅ': 'e',  # FULLWIDTH LATIN SMALL LETTER E
    'ｈ': 'h',  # FULLWIDTH LATIN SMALL LETTER H
    'ｉ': 'i',  # FULLWIDTH LATIN SMALL LETTER I
    'ｊ': 'j',  # FULLWIDTH LATIN SMALL LETTER J
    'ｌ': 'l',  # FULLWIDTH LATIN SMALL LETTER L
    'ｎ': 'n',  # FULLWIDTH LATIN SMALL LETTER N
    'ｏ': 'o',  # FULLWIDTH LATIN SMALL LETTER O
    'ｐ': 'p',  # FULLWIDTH LATIN SMALL LETTER P
    'ｓ': 's',  # FULLWIDTH LATIN SMALL LETTER S
    'ｔ': 't',  # FULLWIDTH LATIN SMALL LETTER T
    'ｕ': 'u',  # FULLWIDTH LATIN SMALL LETTER U
    'ｗ': 'w',  # FULLWIDTH LATIN SMALL LETTER W
    '𝐀': 'A',  # MATHEMATICAL BOLD CAPITAL A
    '𝐁': 'B',  # MATHEMATICAL BOLD CAPITAL B
    '𝐃': 'D',  # MATHEMATICAL BOLD CAPITAL D
    '𝐄': 'E',  # MATHEMATICAL BOLD CAPITAL E
    '𝐆': 'G',  # MATHEMATICAL BOLD CAPITAL G
    '𝐇': 'H',  # MATHEMATICAL BOLD CAPITAL H
    '𝐈': 'I',  # MATHEMATICAL BOLD CAPITAL I
    '𝐊': 'K',  # MATHEMATICAL BOLD CAPITAL K
    '𝐋': 'L',  # MATHEMATICAL BOLD CAPITAL L
    '𝐌': 'M',  # MATHEMATICAL BOLD CAPITAL M
    '𝐍': 'N',  # MATHEMATICAL BOLD CAPITAL N
    '𝐎': 'O',  # MATHEMATICAL BOLD CAPITAL O
    '𝐑': 'R',  # MATHEMATICAL BOLD CAPITAL R
    '𝐒': 'S',  # MATHEMATICAL BOLD CAPITAL S
    '𝐓': 'T',  # MATHEMATICAL BOLD CAPITAL T
    '𝐔': 'U',  # MATHEMATICAL BOLD CAPITAL U
    '𝐕': 'V',  # MATHEMATICAL BOLD CAPITAL V
    '𝐖': 'W',  # MATHEMATICAL BOLD CAPITAL W
    '𝐗': 'X',  # MATHEMATICAL BOLD CAPITAL X
    '𝐘': 'Y',  # MATHEMATICAL BOLD CAPITAL Y
    '𝐚': 'a',  # MATHEMATICAL BOLD SMALL A
    '𝐛': 'b',  # MATHEMATICAL BOLD SMALL B
    '𝐝': 'd',  # MATHEMATICAL BOLD SMALL D
    '𝐞': 'e',  # MATHEMATICAL BOLD SMALL E
    '𝐠': 'g',  # MATHEMATICAL BOLD SMALL G
    '𝐢': 'i',  # MATHEMATICAL BOLD SMALL I
    '𝐣': 'j',  # MATHEMATICAL BOLD SMALL J
    '𝐥': 'l',  # MATHEMATICAL BOLD SMALL L
    '𝐧': 'n',  # MATHEMATICAL BOLD SMALL N
    '𝐨': 'o',  # MATHEMATICAL BOLD SMALL O
    '𝐫': 'r',  # MATHEMATICAL BOLD SMALL R
    '𝐬': 's',  # MATHEMATICAL BOLD SMALL S
    '𝐭': 't',  # MATHEMATICAL BOLD SMALL T
    '𝐲': 'y',  # MATHEMATICAL BOLD SMALL Y
    '𝐴': 'A',  # MATHEMATICAL ITALIC CAPITAL A
    '𝐷': 'D',  # MATHEMATICAL ITALIC CAPITAL D
    '𝐸': 'E',  # MATHEMATICAL ITALIC CAPITAL E
    '𝐺': 'G',  # MATHEMATICAL ITALIC CAPITAL G
    '𝐻': 'H',  # MATHEMATICAL ITALIC CAPITAL H
    '𝐼': 'I',  # MATHEMATICAL ITALIC CAPITAL I
    '𝐿': 'L',  # MATHEMATICAL ITALIC CAPITAL L
    '𝑀': 'M',  # MATHEMATICAL ITALIC CAPITAL M
    '𝑂': 'O',  # MATHEMATICAL ITALIC CAPITAL O
    '𝑅': 'R',  # MATHEMATICAL ITALIC CAPITAL R
    '𝑆': 'S',  # MATHEMATICAL ITALIC CAPITAL S
    '𝑇': 'T',  # MATHEMATICAL ITALIC CAPITAL T
    '𝑈': 'U',  # MATHEMATICAL ITALIC CAPITAL U
    '𝑊': 'W',  # MATHEMATICAL ITALIC CAPITAL W
    '𝑋': 'X',  # MATHEMATICAL ITALIC CAPITAL X
    '𝑨': 'A',  # MATHEMATICAL BOLD ITALIC CAPITAL A
    '𝑪': 'C',  # MATHEMATICAL BOLD ITALIC CAPITAL C
    '𝑫': 'D',  # MATHEMATICAL BOLD ITALIC CAPITAL D
    '𝑮': 'G',  # MATHEMATICAL BOLD ITALIC CAPITAL G
    '𝑰': 'I',  # MATHEMATICAL BOLD ITALIC CAPITAL I
    '𝑲': 'K',  # MATHEMATICAL BOLD ITALIC CAPITAL K
    '𝑳': 'L',  # MATHEMATICAL BOLD ITALIC CAPITAL L
    '𝑴': 'M',  # MATHEMATICAL BOLD ITALIC CAPITAL M
    '𝑵': 'N',  # MATHEMATICAL BOLD ITALIC CAPITAL N
    '𝑶': 'O',  # MATHEMATICAL BOLD ITALIC CAPITAL O
    '𝑺': 'S',  # MATHEMATICAL BOLD ITALIC CAPITAL S
    '𝑻': 'T',  # MATHEMATICAL BOLD ITALIC CAPITAL T
    '𝒀': 'Y',  # MATHEMATICAL BOLD ITALIC CAPITAL Y
    '𝒜': 'A',  # MATHEMATICAL SCRIPT CAPITAL A
    '𝒢': 'G',  # MATHEMATICAL SCRIPT CAPITAL G
    '𝒩': 'N',  # MATHEMATICAL SCRIPT CAPITAL N
    '𝒫': 'P',  # MATHEMATICAL SCRIPT CAPITAL P
    '𝒮': 'S',  # MATHEMATICAL SCRIPT CAPITAL S
    '𝒯': 'T',  # MATHEMATICAL SCRIPT CAPITAL T
    '𝒰': 'U',  # MATHEMATICAL SCRIPT CAPITAL U
    '𝓐': 'A',  # MATHEMATICAL BOLD SCRIPT CAPITAL A
    '𝓘': 'I',  # MATHEMATICAL BOLD SCRIPT CAPITAL I
    '𝓛': 'L',  # MATHEMATICAL BOLD SCRIPT CAPITAL L
    '𝓝': 'N',  # MATHEMATICAL BOLD SCRIPT CAPITAL N
    '𝓟': 'P',  # MATHEMATICAL BOLD SCRIPT CAPITAL P
    '𝓤': 'U',  # MATHEMATICAL BOLD SCRIPT CAPITAL U
    '𝓦': 'W',  # MATHEMATICAL BOLD SCRIPT CAPITAL W
    '𝕂': 'K',  # MATHEMATICAL DOUBLE-STRUCK CAPITAL K
    '𝕒': 'a',  # MATHEMATICAL DOUBLE-STRUCK SMALL A
    '𝕓': 'b',  # MATHEMATICAL DOUBLE-STRUCK SMALL B
    '𝕕': 'd',  # MATHEMATICAL DOUBLE-STRUCK SMALL D
    '𝕖': 'e',  # MATHEMATICAL DOUBLE-STRUCK SMALL E
    '𝕘': 'g',  # MATHEMATICAL DOUBLE-STRUCK SMALL G
    '𝕙': 'h',  # MATHEMATICAL DOUBLE-STRUCK SMALL H
    '𝕚': 'i',  # MATHEMATICAL DOUBLE-STRUCK SMALL I
    '𝕟': 'n',  # MATHEMATICAL DOUBLE-STRUCK SMALL N
    '𝕡': 'p',  # MATHEMATICAL DOUBLE-STRUCK SMALL P
    '𝕣': 'r',  # MATHEMATICAL DOUBLE-STRUCK SMALL R
    '𝕤': 's',  # MATHEMATICAL DOUBLE-STRUCK SMALL S
    '𝕦': 'u',  # MATHEMATICAL DOUBLE-STRUCK SMALL U
    '𝖪': 'K',  # MATHEMATICAL SANS-SERIF CAPITAL K
    '𝖺': 'a',  # MATHEMATICAL SANS-SERIF SMALL A
    '𝖾': 'e',  # MATHEMATICAL SANS-SERIF SMALL E
    '𝗀': 'g',  # MATHEMATICAL SANS-SERIF SMALL G
    '𝗁': 'h',  # MATHEMATICAL SANS-SERIF SMALL H
    '𝗂': 'i',  # MATHEMATICAL SANS-SERIF SMALL I
    '𝗃': 'j',  # MATHEMATICAL SANS-SERIF SMALL J
    '𝗄': 'k',  # MATHEMATICAL SANS-SERIF SMALL K
    '𝗅': 'l',  # MATHEMATICAL SANS-SERIF SMALL L
    '𝗆': 'm',  # MATHEMATICAL SANS-SERIF SMALL M
    '𝗇': 'n',  # MATHEMATICAL SANS-SERIF SMALL N
    '𝗈': 'o',  # MATHEMATICAL SANS-SERIF SMALL O
    '𝗍': 't',  # MATHEMATICAL SANS-SERIF SMALL T
    '𝗎': 'u',  # MATHEMATICAL SANS-SERIF SMALL U
    '𝗒': 'y',  # MATHEMATICAL SANS-SERIF SMALL Y
    '𝗔': 'A',  # MATHEMATICAL SANS-SERIF BOLD CAPITAL A
    '𝗕': 'B',  # MATHEMATICAL SANS-SERIF BOLD CAPITAL B
    '𝗖': 'C',  # MATHEMATICAL SANS-SERIF BOLD CAPITAL C
    '𝗗': 'D',  # MATHEMATICAL SANS-SERIF BOLD CAPITAL D
    '𝗘': 'E',  # MATHEMATICAL SANS-SERIF BOLD CAPITAL E
    '𝗚': 'G',  # MATHEMATICAL SANS-SERIF BOLD CAPITAL G
    '𝗛': 'H',  # MATHEMATICAL SANS-SERIF BOLD CAPITAL H
    '𝗜': 'I',  # MATHEMATICAL SANS-SERIF BOLD CAPITAL I
    '𝗝': 'J',  # MATHEMATICAL SANS-SERIF BOLD CAPITAL J
    '𝗞': 'K',  # MATHEMATICAL SANS-SERIF BOLD CAPITAL K
    '𝗟': 'L',  # MATHEMATICAL SANS-SERIF BOLD CAPITAL L
    '𝗠': 'M',  # MATHEMATICAL SANS-SERIF BOLD CAPITAL M
    '𝗡': 'N',  # MATHEMATICAL SANS-SERIF BOLD CAPITAL N
    '𝗢': 'O',  # MATHEMATICAL SANS-SERIF BOLD CAPITAL O
    '𝗣': 'P',  # MATHEMATICAL SANS-SERIF BOLD CAPITAL P
    '𝗥': 'R',  # MATHEMATICAL SANS-SERIF BOLD CAPITAL R
    '𝗦': 'S',  # MATHEMATICAL SANS-SERIF BOLD CAPITAL S
    '𝗧': 'T',  # MATHEMATICAL SANS-SERIF BOLD CAPITAL T
    '𝗨': 'U',  # MATHEMATICAL SANS-SERIF BOLD CAPITAL U
    '𝗪': 'W',  # MATHEMATICAL SANS-SERIF BOLD CAPITAL W
    '𝗬': 'Y',  # MATHEMATICAL SANS-SERIF BOLD CAPITAL Y
    '𝗮': 'a',  # MATHEMATICAL SANS-SERIF BOLD SMALL A
    '𝗲': 'e',  # MATHEMATICAL SANS-SERIF BOLD SMALL E
    '𝗴': 'g',  # MATHEMATICAL SANS-SERIF BOLD SMALL G
    '𝗶': 'i',  # MATHEMATICAL SANS-SERIF BOLD SMALL I
    '𝗹': 'l',  # MATHEMATICAL SANS-SERIF BOLD SMALL L
    '𝗺': 'm',  # MATHEMATICAL SANS-SERIF BOLD SMALL M
    '𝗻': 'n',  # MATHEMATICAL SANS-SERIF BOLD SMALL N
    '𝗼': 'o',  # MATHEMATICAL SANS-SERIF BOLD SMALL O
    '𝗿': 'r',  # MATHEMATICAL SANS-SERIF BOLD SMALL R
    '𝘀': 's',  # MATHEMATICAL SANS-SERIF BOLD SMALL S
    '𝘂': 'u',  # MATHEMATICAL SANS-SERIF BOLD SMALL U
    '𝘄': 'w',  # MATHEMATICAL SANS-SERIF BOLD SMALL W
    '𝘆': 'y',  # MATHEMATICAL SANS-SERIF BOLD SMALL Y
    '𝘈': 'A',  # MATHEMATICAL SANS-SERIF ITALIC CAPITAL A
    '𝘋': 'D',  # MATHEMATICAL SANS-SERIF ITALIC CAPITAL D
    '𝘌': 'E',  # MATHEMATICAL SANS-SERIF ITALIC CAPITAL E
    '𝘎': 'G',  # MATHEMATICAL SANS-SERIF ITALIC CAPITAL G
    '𝘏': 'H',  # MATHEMATICAL SANS-SERIF ITALIC CAPITAL H
    '𝘓': 'L',  # MATHEMATICAL SANS-SERIF ITALIC CAPITAL L
    '𝘔': 'M',  # MATHEMATICAL SANS-SERIF ITALIC CAPITAL M
    '𝘖': 'O',  # MATHEMATICAL SANS-SERIF ITALIC CAPITAL O
    '𝘙': 'R',  # MATHEMATICAL SANS-SERIF ITALIC CAPITAL R
    '𝘚': 'S',  # MATHEMATICAL SANS-SERIF ITALIC CAPITAL S
    '𝘛': 'T',  # MATHEMATICAL SANS-SERIF ITALIC CAPITAL T
    '𝘜': 'U',  # MATHEMATICAL SANS-SERIF ITALIC CAPITAL U
    '𝘞': 'W',  # MATHEMATICAL SANS-SERIF ITALIC CAPITAL W
    '𝘟': 'X',  # MATHEMATICAL SANS-SERIF ITALIC CAPITAL X
    '𝘦': 'e',  # MATHEMATICAL SANS-SERIF ITALIC SMALL E
    '𝘬': 'k',  # MATHEMATICAL SANS-SERIF ITALIC SMALL K
    '𝘶': 'u',  # MATHEMATICAL SANS-SERIF ITALIC SMALL U
    '𝘼': 'A',  # MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL A
    '𝘽': 'B',  # MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL B
    '𝘿': 'D',  # MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL D
    '𝙀': 'E',  # MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL E
    '𝙁': 'F',  # MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL F
    '𝙂': 'G',  # MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL G
    '𝙃': 'H',  # MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL H
    '𝙄': 'I',  # MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL I
    '𝙆': 'K',  # MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL K
    '𝙇': 'L',  # MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL L
    '𝙈': 'M',  # MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL M
    '𝙉': 'N',  # MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL N
    '𝙊': 'O',  # MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL O
    '𝙋': 'P',  # MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL P
    '𝙍': 'R',  # MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL R
    '𝙎': 'S',  # MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL S
    '𝙏': 'T',  # MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL T
    '𝙐': 'U',  # MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL U
    '𝙒': 'W',  # MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL W
    '𝙓': 'X',  # MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL X
    '𝙔': 'Y',  # MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL Y
    '𝙶': 'G',  # MATHEMATICAL MONOSPACE CAPITAL G
    '𝚊': 'a',  # MATHEMATICAL MONOSPACE SMALL A
    '𝚋': 'b',  # MATHEMATICAL MONOSPACE SMALL B
    '𝚝': 't',  # MATHEMATICAL MONOSPACE SMALL T
    '𝚞': 'u',  # MATHEMATICAL MONOSPACE SMALL U
    '𝟎': '0',  # MATHEMATICAL BOLD DIGIT ZERO
    '𝟏': '1',  # MATHEMATICAL BOLD DIGIT ONE
    '𝟐': '2',  # MATHEMATICAL BOLD DIGIT TWO
    '𝟑': '3',  # MATHEMATICAL BOLD DIGIT THREE
    '𝟒': '4',  # MATHEMATICAL BOLD DIGIT FOUR
    '𝟕': '7',  # MATHEMATICAL BOLD DIGIT SEVEN
    '𝟖': '8',  # MATHEMATICAL BOLD DIGIT EIGHT
    '𝟩': '7',  # MATHEMATICAL SANS-SERIF DIGIT SEVEN
    '𝟪': '8',  # MATHEMATICAL SANS-SERIF DIGIT EIGHT
    '𝟮': '2',  # MATHEMATICAL SANS-SERIF BOLD DIGIT TWO
    '𝟳': '7',  # MATHEMATICAL SANS-SERIF BOLD DIGIT SEVEN
    '𝟴': '8',  # MATHEMATICAL SANS-SERIF BOLD DIGIT EIGHT
    '𝟵': '9',  # MATHEMATICAL SANS-SERIF BOLD DIGIT NINE
    '𝟽': '7',  # MATHEMATICAL MONOSPACE DIGIT SEVEN
    '𝟾': '8',  # MATHEMATICAL MONOSPACE DIGIT EIGHT
}

def normalize_homoglyph(text):
    """Normalize homoglyph characters to normal ASCII"""
    for homo, normal in HOMOGLYPH_MAP.items():
        text = text.replace(homo, normal)
    return text
